version: "3"

services:
  # Etcd注册中心
  etcd:
    image: "bitnami/etcd:3.4.3"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - ETCD_NAME=default
      - ETCD_DATA_DIR=default.etcd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    #ports:
    #- 2379:2379
    #- 2380:2380
    volumes:
      - etcddata:/default.etcd
    networks:
      - starter-kit-console

  elasticsearch:
    image: "elasticsearch:7.7.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - starter-kit-console

  fluentbit:
    image: "fluent/fluent-bit:1.4"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - starter-kit-console

  # API网关
  gateway:
    depends_on:
      - etcd
      - fluentbit
    command: --registry=etcd --registry_address=etcd:2379 --transport=tcp gateway --address=:8080
    image:  "registry.cn-hangzhou.aliyuncs.com/hb-chen/starter-kit-gateway:latest"
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: starter-kit-console-gateway
        fluentd-async-connect: 'true'
    volumes:
      - ./account/conf:/conf
    ports:
      - "8080:8080"
    networks:
      - starter-kit-console

  # Console Web服务
  web:
    depends_on:
      - etcd
      - fluentbit
    command: --registry=etcd --registry_address=etcd:2379 --transport=tcp
    #image: ""
    build: ./web
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: starter-kit-console-web
        fluentd-async-connect: 'true'
    #volumes:
    #- ./conf:/conf:rw
    networks:
      - starter-kit-console

  # Console API服务
  api:
    depends_on:
      - etcd
      - fluentbit
    command: --registry=etcd --registry_address=etcd:2379 --transport=tcp
    #image: ""
    build: ./api
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: starter-kit-console-api
        fluentd-async-connect: 'true'
    #volumes:
    #- ./conf:/conf
    networks:
      - starter-kit-console

  # Account SRV服务
  account:
    depends_on:
      - etcd
      - fluentbit
    command: --registry=etcd --registry_address=etcd:2379 --transport=tcp
    #image: ""
    build: ./account
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: starter-kit-console-account
        fluentd-async-connect: 'true'
    volumes:
      - ./account/conf:/conf
    networks:
      - starter-kit-console

networks:
  starter-kit-console:
    external: true

volumes:
  etcddata:
